/******************************************************************************
 * @Author                : adolnb<loro.lorenzonunez@gmail.com>               *
 * @CreatedDate           : 2025-11-19 05:17:22                               *
 * @LastEditors           : adolnb<loro.lorenzonunez@gmail.com>               *
 * @LastEditDate          : 2025-11-20 06:48:08                               *
 * @FilePath              : layout.tsx                                        *
 * @CopyRight             : © 2025 Adonai LN - B0MB0                          *
 *****************************************************************************/

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoadingComponent from "@/components/ui/Loading";
import ToastComponent from "@/components/ui/Toast";
import { images } from "@/constants/images";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: "Colibri | Panel Administrativo",
  description: "Panel administrativo Colibri",
  keywords: ["colibri", "administración", "transportes", "dashboard", "arroyo seco"],
  authors: [{ name: "adobln", url: "https://github.com/adolnb" }],
  icons: {
    icon: images.logos.transparentColibri,
    shortcut: images.logos.transparentColibri,
    apple: images.logos.transparentColibri,
  },
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
      <body>
        {children}
        <LoadingComponent />
        <ToastComponent />
      </body>
    </html>
  );
};
